use jk

alter  table  transactions
alter  column  qty  numeric

alter table   transactions
alter  column rate  numeric

alter  table  transactions
alter column  tax  numeric

alter  table  transactions
alter column  total_amt  numeric


--Data Preparation And Understanding.

--Q1: WHAT IS THE TOTAL NUMBER OF ROWS IN EACH OF THE 3 TABLES IN THE DATABASE?
	select COUNT (*) TotalNumOfRows from Customer
	select COUNT (*) TotalNumOfRows from prod_cat_info
	select COUNT (*) TotalNumOfRows from Transactions

	
--Q2: WHAT IS THE TOTAL NO. OF TRANSACTIONS THAT HAVE A RETURN ?
	select count(total_amt)[TotalNumOfTransaction] from Transactions
	where total_amt like '-%'

--Q3: As you would have noticed, the dates provided across the data sets are not in a correct format.As a first
 select CONVERT(Date , DOB, 105) as Dates from Customer
select CONVERT(Date, tran_date, 105) as Dates from Transactions


---Q4: What is the time range of the transaction data available for analysis ?
select DATEDIFF(Day, Min(convert(Date, tran_date,105)),
Max(convert(date, tran_date,105)))[NumberOfDays],
datediff(month,min(convert(date,tran_date,105)),
Max(convert(date, tran_date, 105)))[NumberOfMonths],
datediff(year,min(convert(date,tran_date,105)),
MAX(Convert(date,tran_date,105))) [NumberOfYears]
from Transactions

--Q5: Which product category does the sub-category "DIY" belongs to ? 
select* from prod_cat_info
where prod_subcat like 'DIY'

------------------------------Data Analysis------------------------------

--Q1: WHICH CHANNEL IS MOST FREQUENTLY USED FOR TRANSACTIONS ?
select top 1  Store_type, count(transaction_id) [CountofId] from Transactions
group by Store_type
order by COUNT(transaction_id) desc
	
--Q2 WHAT IS  THE COUNT OF MALE AND FEMALE CUSTOMERS IN THE DATABASE ?	
 select Gender, count(customer_Id) as CountOfGender from Customer
 where Gender in ('M' , 'F')
 group by Gender

--Q3: From Which city do we have a maximum number of customers and how many ?
select top 1 city_code, count(customer_id) cust_cnt from Customer
group by city_code
order by cust_cnt desc

--Q4: How many sub-categories are there under Books category ?
select count(prod_subcat) as SubCategoriesCount from prod_cat_info
where prod_cat = 'Books'
group by prod_cat


--Q5: What is the Maximum quantity of the product ever ordered 
select cust_id, sum(Qty)[QuantityMax] from Transactions
group by cust_id


--Q6: What is the net total revenue generated in Categories Electronics and Books ?
select  sum(total_amt) [TotalAmount] from Transactions t 
inner join prod_cat_info p on t.prod_cat_code = p.prod_cat_code 
and t.prod_subcat_code = p.prod_sub_cat_code
where prod_cat in ('BOOKS', 'ELECTRONICS')


--Q7: How many customers have >10 transacations wih us , excluding returns ?
select COUNT(customer_id) as CountofCustomer from Customer 
where customer_Id in ( select  cust_id from Transactions left join Customer on customer_Id = cust_id
where total_amt not like '-%' 
group by cust_id 
having count(transaction_id) > 10 )

--Q8: What is the czombined revenue earned from "Electronics" and "Clothing" categories from "Flagship Stores"?
select SUM(total_amt) as amount from Transactions t inner join prod_cat_info pci on t.prod_cat_code = pci.prod_cat_code
and prod_sub_cat_code = prod_subcat_code
where prod_cat in ('Clothing','Electronics') and Store_type = 'Flagship Store'

 
--Q9: What is the total revenue generated from "Male" customers in "Electronics" category? Output should display total revenue by prod_sub-cat.*/
select prod_subcat,sum(total_amt) [Total Revenue] from Customer c inner join Transactions t  on c.customer_Id= t.cust_id
inner join prod_cat_info pci on t.prod_cat_code = pci.prod_cat_code and t.prod_subcat_code = pci.prod_sub_cat_code
where Gender ='M' and prod_cat='Electronics'
group by prod_subcat


--Q10: What is the percentage of sales and returns by product sub category;display only top five categories in terms of sales?
select  top 5 prod_subcat, (sum(total_amt)/(Select sum(total_amt) from Transactions))*100 as SalesPercentage,
(COUNT(case when qty<0 then qty else null end)/sum(qty))*100 as PercetageOfReturn
from Transactions t
inner join prod_cat_info pci on t.prod_cat_code = pci.prod_cat_code and prod_subcat_code= prod_sub_cat_code
group by prod_subcat
order by sum(total_amt) desc

-- Q11: For all customers aged between 25and 35 years find out what is the net total revenue generated by these consumers in the last 30 days of 
select CUST_ID,sum(TOTAL_AMT) AS TotalRevenue FROM Transactions
where CUST_ID IN (select CUSTOMER_ID FROM Customer Where datediff(year,CONVERT(DATE,DOB,103),GETDATE()) BETWEEN 25 AND 35)
AND CONVERT(DATE,tran_date,103) BETWEEN Dateadd(Day,-30,(select Max(CONVERT(date,tran_date,103)) FROM Transactions)) AND
(select MAX(convert(DATE,tran_date,103)) FROM Transactions)
Group by CUST_ID


--Q12: Which product category has seen the maximum value of returns in the last 3 months of the transactions ?
select top 1 prod_cat , sum(total_amt)[TotalAmount]from Transactions t inner join prod_cat_info pci on t.prod_cat_code = pci.prod_cat_code
and t.prod_subcat_code = pci.prod_sub_cat_code 
where total_amt < 0 and convert (date, tran_date,103) between dateadd(month,-3,(select max(convert(date,tran_date,103)) from Transactions))
and (select max (convert(date,tran_date,103)) from Transactions)
group by prod_cat
order by [TotalAmount] desc


--Q13: Which store-type sells the maximum products; by value of sales amount and by quantity sold ?
 select Store_type,sum(total_amt) [TotalSales], sum(Qty) [TotalQuantity] from Transactions
 group by Store_type
 having sum(total_amt) >=All  (select sum(total_amt) from Transactions group by Store_type) and 
 sum(qty) >=all (select sum(qty) from Transactions group by Store_type)


--Q14: what are the categories for which the average revenue is above the overll average ?
select prod_cat ,AVG(total_amt) as average from Transactions t inner join prod_cat_info pci on t.prod_cat_code = pci.prod_cat_code and
pci.prod_sub_cat_code = t.prod_subcat_code 
group by prod_cat
having avg(total_amt) > (select avg(total_amt) from Transactions)


--Q15: Find the average and the total revenue by each sub category for the categories whch are among top 5 categories in terms of quantities sold ?
select prod_cat,prod_subcat, avg(total_amt) [AverageRevenue],sum(total_amt) [TotalRevenue] from Transactions t
inner join prod_cat_info pci on pci.prod_cat_code = t.prod_cat_code and prod_sub_cat_code = prod_subcat_code 
where prod_cat in (select top 5 prod_cat from Transactions t1 inner join prod_cat_info pci1 on t1.prod_cat_code=pci1.prod_cat_code and prod_sub_cat_code = prod_subcat_code
group by prod_cat
order by sum(qty) desc)
group by prod_cat, prod_subcat
